### ISSUE TITLE
Installation error with pyx

### ISSUE THREAD

**Issue by jykr** [pinellolab/crispr-bean#26]
Copying error report from Elijah Login Mena @BWH

just want to let you know I had a minor issues installing bean on my computer yesterday. What worked for me was adding the following two lines to the beginning of the 
CRISPResso2Align.pyx
file:
```
from numpy cimport import_array
import_array()
```

Otherwise I got the following error message:
```
>>>
 import bean Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/Users/emena/Dropbox .../crispr-bean/bean/__init__.py", line 3, in <module> from . import mapping as mp File "/Users/emena/Dropbox
.../crispr-bean/bean/mapping/__init__.py", line 1, in <module> from .GuideEditCounter import GuideEditCounter File "/Users/user/Dropbox .../crispr-bean/bean/mapping/GuideEditCounter.py",
 line 16, in <module> from ._supporting_fn import ( File "/Users/user/Dropbox .../crispr-bean/bean/mapping/_supporting_fn.py", line 9, in <module> from bean.mapping.CRISPResso2Align import read_matrix, global_align_base_editor
 File "bean/mapping/CRISPResso2Align.pyx", line 1, in init bean.mapping.CRISPResso2Align # Copied & modified from CRISPResso2 https://github.com/pinellolab/CRISPResso2/blob/master/CRISPResso2/CRISPResso2Align.pyx ImportError: numpy.core.multiarray failed to
 import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by jykr** [comment]
Seems to be related to numpy (https://github.com/tensorflow/tensorflow/issues/559), please reopen if the update does not resolve the issue (without modifying CRISPResso2Align.pyx)

**Comment by jykr** [comment]
This error happens with unspecified bases in FASTQ, leading to alignment score over/underflow. Currently `bean` only supports A/C/T/G for bases. If you need to accommodate special bases, please edit `output_path/.aln_mat.txt` (https://github.com/pinellolab/crispr-bean/blob/fb6766796f751cd77e3998dc814e18ef97c7eb26/bean/mapping/GuideEditCounter.py#L248).
